version: "4.0"
services:
  www:
    build: .
    volumes:
      - ./app:/var/www/html/
    ports:
      - 8000:80

  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8002:80
    environment:
      - PMA_HOST=mysql_db
      - PMA_PORT=3306
